"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var bodyParser = require("body-parser");
var router_1 = require("./src/router");
var app = express();
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.json({ limit: '10MB' }));
app.use('/', router_1.default);
exports.default = app;
